In [1]:
import pandas as pd
df = pd.read_csv('CAR DETAILS FROM CAR DEKHO.csv')
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [7]:
df = df[['year',	'selling_price',	'km_driven']]

In [8]:
X = df.drop('selling_price',axis=1)
y= df['selling_price']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [10]:
X_train.shape

(3472, 2)

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [12]:
scaled_X_train

array([[0.89285714, 0.02479426],
       [0.92857143, 0.06198751],
       [0.75      , 0.03099313],
       ...,
       [0.85714286, 0.06322728],
       [0.75      , 0.09918076],
       [0.75      , 0.09918076]], shape=(3472, 2))

In [14]:
scaled_X_train = pd.DataFrame(data=scaled_X_train, columns=X_train.columns)
scaled_X_test = pd.DataFrame(data=scaled_X_test, columns=X_test.columns)

In [15]:
scaled_X_train

          year  km_driven
0     0.892857   0.024794
1     0.928571   0.061988
2     0.750000   0.030993
3     0.678571   0.086783
4     0.892857   0.089263
...        ...        ...
3467  0.500000   0.061988
3468  0.678571   0.099181
3469  0.857143   0.063227
3470  0.750000   0.099181
3471  0.750000   0.099181

[3472 rows x 2 columns]